
# AGE08: ¿Qué eventos están dirigidos a un público adulto?

PREFIX edintagenda: <https://edint.es/def/agenda#>
PREFIX schema: <https://schema.org/>

SELECT ?event ?name
WHERE {
  ?event a edintagenda:CityEvent ;
         schema:audience ?audience .

  OPTIONAL { ?event schema:name ?name }

  # Filtrar público adulto
  FILTER(CONTAINS(LCASE(?audience), "adult"))
}
